USE IITMDSAIDB
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE NAME = 'SOFTWARE' AND xtype = 'U')
CREATE TABLE [dbo].[SOFTWARE] (
   [PNAME] VARCHAR(30) NULL,
   [TITLE] VARCHAR(30) NULL,
   [DEVELOPIN] VARCHAR(20) NULL,
 --[SCOST] INT NULL,
   [SCOST] DECIMAL(7,2) NULL,
   [DCOST] INT NULL,
   [SOLD] INT NULL
)
GO

--ALTER TABLE [dbo].[SOFTWARE]
--ALTER COLUMN [SCOST] DECIMAL(7,2)

INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('MARY', 'README', 'CPP', 300, 1200, 84);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('ANAND', 'PARACHUTES', 'BASIC', 399.95, 6000, 43);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('ANAND', 'VIDEO TITLING', 'PASCAL', 7500, 16000, 9);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('JULIANA', 'INVENTORY', 'COBOL', 3000, 3500, 0);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('KAMALA', 'PAYROLL PKG.', 'DBASE', 9000, 20000, 7);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('MARY', 'FINANCIAL ACCT.', 'ORACLE', 18000, 85000, 4);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('MARY', 'CODE GENERATOR', 'C', 4500, 20000, 23);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('PATTRICK', 'README', 'CPP', 300, 1200, 84);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('QADIR', 'BOMBS AWAY', 'ASSEMBLY', 750, 3000, 11);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('QADIR', 'VACCINES', 'C', 1900, 3100, 21);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('RAMESH', 'HOTEL MGMT.', 'DBASE', 13000, 35000, 4);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('RAMESH', 'DEAD LEE', 'PASCAL', 599.95, 4500, 73);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('REMITHA', 'PC UTILITIES', 'C', 725, 5000, 51);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('REMITHA', 'TSR HELP PKG.', 'ASSEMBLY', 2500, 6000, 7);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('REVATHI', 'HOSPITAL MGMT.', 'PASCAL', 1100, 75000, 2);
INSERT INTO [dbo].[SOFTWARE] ([PNAME], [TITLE], [DEVELOPIN], [SCOST], [DCOST], [SOLD]) VALUES ('VIJAYA', 'TSR EDITOR', 'C', 900, 700, 6);
