USE IITMDSAIDB
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE NAME = 'STUDIES' AND xtype = 'U')
CREATE TABLE [dbo].[STUDIES] (
   [PNAME] VARCHAR(30) NULL,
   [INSTITUTE] VARCHAR(30) NULL,
   [COURSE] VARCHAR(15) NULL,
   [COURSE FEE] INT NULL,
)
GO


INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('ANAND', 'SABHARI', 'PGDCA', 4500);
INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('ALTAF', 'COIT', 'DCA', 7200);
INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('JULIANA', 'BDPS', 'MCA', 22000);
INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('KAMALA', 'PRAGATHI', 'DCA', 5000);
INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('MARY', 'SABHARI', 'PGDCA', 4500);
INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('NELSON', 'PRAGATHI', 'DAP', 6200);
INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('PATRICK', 'PRAGATHI', 'DCAP', 5200);
INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('QADIR', 'APPLE', 'HDCA', 14000);
INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('RAMESH', 'SABHARI', 'PGDCA', 4500);
INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('REBECCA', 'BRILLIANT', 'DCAP', 11000);
INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('REMITHA', 'BDPS', 'DCS', 6000);
INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('REVATHI', 'SABHARI', 'DAP', 5000);
INSERT INTO [dbo].[STUDIES] ([PNAME], [INSTITUTE], [COURSE], [COURSE FEE]) VALUES ('VIJAYA', 'BDPS', 'DCA', 48000);
