USE IITMDSAIDB
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE NAME = 'STUDIES' AND xtype = 'U')
CREATE TABLE [dbo].[STUDIES] (
   [PNAME] VARCHAR(30) NULL,
   [INSTITUTE] VARCHAR(30) NULL,
   [COURSE] VARCHAR(15) NULL,
   [COURSE FEE] INT NULL,
)
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE NAME = 'SOFTWARE' AND xtype = 'U')
CREATE TABLE [dbo].[SOFTWARE] (
   [PNAME] VARCHAR(30) NULL,
   [TITLE] VARCHAR(30) NULL,
   [DEVELOPIN] VARCHAR(20) NULL,
 --[SCOST] INT NULL,
   [SCOST] DECIMAL(7,2) NULL,
   [DCOST] INT NULL,
   [SOLD] INT NULL
)
GO

--ALTER TABLE [dbo].[SOFTWARE]
--ALTER COLUMN [SCOST] DECIMAL(7,2)

IF NOT EXISTS (SELECT * FROM sysobjects WHERE NAME = 'PROGRAMMER' AND xtype = 'U')
CREATE TABLE [dbo].[PROGRAMMER] (
   [PNAME] VARCHAR(30) NULL,
   [DOB] DATE NULL,
   [DOJ] DATE NULL,
 --[GENDER]  VARCHAR(30) NULL,
   [GENDER]  VARCHAR(1) NULL,
   [PROF1]  VARCHAR(30) NULL,
   [PROF2] VARCHAR(30) NULL,
   [SALARY] INT NULL
)
GO

--ALTER TABLE [dbo].[PROGRAMMER]
--ALTER COLUMN [GENDER] VARCHAR(1)

IF NOT EXISTS (SELECT * FROM sysobjects WHERE NAME = 'CUSTOMER' AND xtype = 'U')
CREATE TABLE [dbo].[CUSTOMER] (
   [CUSTOMER_ID] INT,
   [FIRST_NAME] VARCHAR(30) NULL,
   [LAST_NAME] VARCHAR(30) NULL,
   [EMAIL] VARCHAR(50) NULL,
   [ADDRESS] VARCHAR(50) NULL,
   [CITY]  VARCHAR(30) NULL,
   [STATE]  VARCHAR(30) NULL,
   [ZIP CODE] INT NULL
)
GO

INSERT INTO [dbo].[CUSTOMER] ([CUSTOMER_ID], [FIRST_NAME], [LAST_NAME], [EMAIL], [ADDRESS], [CITY], [STATE], [ZIP CODE]) 
VALUES 
(1, 'SARDHAR', 'PATEL', 'SARDHAR.PATEL@INDIANSTHEBEST.com', 'Railway Colony Road', 'Swai Madopur', 'Rajasthan', 322001),
(2, 'ALTAF', 'JULIANA', 'ALTAF.JULIANA@INDIANSTHEBEST.com', 'N Caswell St', 'La Grange', 'North Carolina', 28551),
(3, 'JULIANA', 'NELSON', 'JULIANA.NELSON@INDIANSTHEBEST.com', 'E 6th Avenue', 'Anchorage', 'Alaska', 99501),
(4, 'KAMALA', 'SANKAR', 'KAMALA.SANKAR@INDIANSTHEBEST.com', 'Lodhi Road', 'New Delhi', 'New Delhi', 110001),
(5, 'MARY', 'JAMES', 'MARY.JAMES@INDIANSTHEBEST.com', 'Park Avenue', 'Moody', 'Alabama', 35004),
(6, 'NELSON', 'PATRICK', 'NELSON.PATRICK@INDIANSTHEBEST.com', '2nd Main Road', 'CHENNAI', 'TAMIL NADU', 600020),
(7, 'GANESH', 'SHIVA KUMAR', 'PATTRICK.NELSON_JR@INDIANSTHEBEST.com', 'Palladam-Dharapuram Rd', 'COIMBATORE', 'TAMIL NADU', 641607),
(8, 'QADIR', 'AHAMED', 'QADIR.AHAMED@INDIANSTHEBEST.com', 'Abhayapuri - Srijangram Rd', 'BONGAIGAON', 'ASSAM', 783384),
(9, 'RAJ', 'SANVAL', 'RAJ.SANVAL@INDIANSTHEBEST.com', 'Kerepalya Main Rd', 'ANGALORE', 'KARNATAKA', 560056),
(10, 'REBECCA', 'NELSON', 'REBECCA.NELSON@INDIANSTHEBEST.com', 'Morgan Dr', 'New Gascony', 'Arkansas', 71601),
(11, 'REMITHA', 'SINGH', 'REMITHA.SINGH@INDIANSTHEBEST.com', 'Mukkathu Temple Rd', 'ALAPPUZHA', 'KERALA', 690527),
(12, 'REVATHI', 'RAGHURAM', 'REVATHI.RAGHURAM@INDIANSTHEBEST.com', 'Piler Bhakarapet Rd', 'CHITTOOR', 'ANDHRA PRADESH', 517214),
(13, 'VIJAYA', 'VASAN', 'VIJAYA.VASAN@INDIANSTHEBEST.com', 'Sanjay Bagul Path', 'AHMED NAGAR', 'MAHARASHTRA', 413709);

SELECT * 
  FROM [dbo].[CUSTOMER]
